kind: ConfigMap
apiVersion: v1
metadata:
  name: presto-cfg
data:
  config.properties.coordinator: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=8GB
    query.max-total-memory-per-node=10GB
    query.max-stage-count=200
    task.writer-count=4
    discovery-server.enabled=true
    discovery.uri=http://presto:8080

  config.properties.worker: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=200GB
    query.max-memory-per-node=10GB
    query.max-total-memory-per-node=10GB
    query.max-stage-count=200
    task.writer-count=4
    discovery.uri=http://presto:8080

  hive.properties.template: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://metastore:9083

    hive.allow-drop-table=true
    hive.max-partitions-per-scan=1000000
    hive.compression-codec=NONE

    hive.s3.endpoint=s3.amazonaws.com
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=true
    hive.s3.max-connections=100

  node.properties.template: |
    node.environment=test
    node.data-dir=/var/presto/data
    spiller-spill-path=/tmp
    max-spill-per-node=4TB
    query-max-spill-per-node=1TB
