---
apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  ports:
  - port: 8080
  selector:
    app: presto-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
spec:
  selector:
    matchLabels:
      app: presto-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: metastore
        image: markthebault/fb-presto
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: secret-key
        - name: ARM_SA_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account
        - name: ARM_SA_KEY
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account-key
        volumeMounts:
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.coordinator
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/node.properties.template
          subPath: node.properties.template
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/catalog/hive.properties.template
          subPath: hive.properties.template
        command: ['/opt/autoconfig_and_launch.sh']
        imagePullPolicy: Always
      volumes:
        - name: presto-cfg-vol
          configMap:
            name: presto-cfg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: presto-worker
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: metastore
        image: markthebault/fb-presto
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: secret-key
        - name: ARM_SA_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account
        - name: ARM_SA_KEY
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account-key
        volumeMounts:
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.worker
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/node.properties.template
          subPath: node.properties.template
        - name: presto-cfg-vol
          mountPath: /opt/presto-server/etc/catalog/hive.properties.template
          subPath: hive.properties.template
        command: ['/opt/autoconfig_and_launch.sh']
        imagePullPolicy: Always
      volumes:
        - name: presto-cfg-vol
          configMap:
            name: presto-cfg
---
apiVersion: v1
kind: Pod
metadata:
  name: presto-cli
spec:
  containers:
  - name: presto-cli
    image: markthebault/presto-cli
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
  restartPolicy: Always
