apiVersion: v1
kind: Service
metadata:
  name: {{ include "presto.fullname" . }}
  labels:
    {{- include "presto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "presto.selectorLabelsCoordinator" . | nindent 4 }}
