{{- if .Values.prestoCli.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "presto.fullname" . }}-cli
spec:
  containers:
  - name: presto-cli
    image: "{{ .Values.prestoCli.image }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: Always
  restartPolicy: Always
{{- end -}}