---
apiVersion: v1
kind: Service
metadata:
  name: metastore-db
spec:
  ports:
  - port: 13306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: "mariadb:10.4.3"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
        - name: MYSQL_DATABASE
          value: metastore_db
        ports:
        - containerPort: 3306
          name: mysql

