{{ $dbPass := "MyAwesomePassword123" }}
releases:
############## PRESTO
  - name: mariadb-metastore-backend
    chart: bitnami/mariadb
    version: 9.0.1
    installed: true
    set:
      - name: auth.database
        value: metastore_db
      - name: auth.rootPassword
        value: {{ $dbPass }}
      - name: primary.persistence.storageClass
        value: managed-premium

  - name: hive-metastore
    chart: ../../charts/hive-metastore
    installed: true
    set:
      - name: mysqlBackend.host
        value: mariadb-metastore-backend
      - name: mysqlBackend.password
        value: {{ $dbPass }}
    values:
      - hiveConf: 
          metastoreWarehouseDir: abfss://raw@fsmthdlk.dfs.core.windows.net/warehouse/
          coreSiteExtras:
            coreSiteExtras:
            fs.s3a.connection.ssl.enabled: false
            fs.s3a.endpoint: s3.amazonaws.com
            fs.s3a.fast.upload: true
            fs.azure.account.auth.type.fsmthdlk.dfs.core.windows.net: SharedKey
            fs.azure.account.key.fsmthdlk.dfs.core.windows.net: $ARM_SA_KEY
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: secret-key
        - name: ARM_SA_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account
        - name: ARM_SA_KEY
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account-key
  
  - name: presto
    chart: ../../charts/presto-chart
    installed: true
    values:
      - hiveProperties:
          connector.name: hive-hadoop2
          hive.metastore.uri: thrift://hive-metastore:9083

          hive.allow-drop-table: true
          hive.max-partitions-per-scan: "1000000"
          hive.compression-codec: NONE

          hive.s3.endpoint: s3.amazonaws.com
          hive.s3.path-style-access: true
          hive.s3.ssl.enabled: true
          hive.s3.max-connections: 100
      - globalEnvs:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: secret-key
        - name: ARM_SA_NAME
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account
        - name: ARM_SA_KEY
          valueFrom:
            secretKeyRef:
              name: azure-sa-keys
              key: storage-account-key
      - workers:
          autoscaling:
            enabled: true
          resources:
            limits:
              cpu: 3600m
              memory: 7370Mi
            requests:
              cpu: 1800m
              memory: 3690Mi
      - coordinator:
          resources:
            limits:
              cpu: 3600m
              memory: 7370Mi
            requests:
              cpu: 1800m
              memory: 3690Mi


################ METABASE

  - name: mariadb-metabase-backend
    chart: bitnami/mariadb
    version: 9.0.1
    installed: true
    set:
      - name: auth.database
        value: metabase
      - name: auth.rootPassword
        value: {{ $dbPass }}
      - name: primary.persistence.storageClass
        value: managed-premium

  - name: metabase
    chart: pmint93/metabase
    version: 0.13.1
    installed: true
    values:
      - database:
          type: mysql
          host: mariadb-metabase-backend
          port: 3306
          username: root
          password: {{ $dbPass }}
          dbname: metabase